c_nutra/config/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^$', TemplateView.as_view(
                           template_name='home.html'), name='home'),
                       url(r'^grappelli/', include('grappelli.urls')), # grappelli URLS                       
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^password-reset/', include(
                           'password_reset.urls')),

                       # Accounts urls
                       url(r'accounts/login/$',
                           'django.contrib.auth.views.login', name='login'),
                       url(r'accounts/logout/$', 'django.contrib.auth.views.logout',
                           {'next_page': 'home'}, name='logout'),
                       url(r'accounts/register/$',
                           'apps.users.views.user_register', name='register'),
                       url(r'accounts/profile/$',
                           'apps.users.views.user_profile', name='profile'),
                       url(r'accounts/stats/$',
                           'apps.users.views.user_stats', name='stats'),

                       # Surveys urls
                       url(r'^surveys/', include(
                           'apps.surveys.urls', namespace="surveys")),
                       )

# Uncomment the next line to serve media files in dev.
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns += patterns('',
#                             url(r'^__debug__/', include(debug_toolbar.urls)),
#                             )

c_nutra/apps/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

# Will be deprecated with django-registration
class UserRegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

# User's personal information form
class UserForm(forms.Form):
    username = forms.CharField(required=False)
    email = forms.EmailField(
        required=False,
        error_messages={
            'invalid': u'Formato incorrecto de email.'
        }
    )
    first_name = forms.CharField(required=False)
    last_name = forms.CharField(required=False)

# User's profile form
class UserProfileForm(forms.Form):
    birthday = forms.DateField(
        required=False,
        input_formats=["%d-%m-%Y"],
        error_messages={
            'invalid': u'El formato de la fecha es dd-mm-yyyy.'
        }
    )
    gender = forms.CharField(
        required=False,
        widget=forms.Select(
            choices=(
                            ('M', 'Masculino'),
                            ('F', 'Femenino')
            )
        )
    )
    height = forms.IntegerField(
        required=False,
        min_value=1,
        error_messages={
            'invalid': u'Esto no pasa con html5.',
            'min_value': u'La altura no puede ser negativa.'
        }
    )
    weight = forms.IntegerField(
        required=False,
        min_value=1,
        error_messages={
            'invalid': u'Esto no pasa con html5.',
            'min_value': u'El peso no puede ser negativo.'
        }
    )
    elbow_diameter = forms.IntegerField(
        required=False,
        min_value=1,
        error_messages={
            'invalid': u'Esto no pasa con html5.',
            'min_value': u'El diametro del codo no puede ser negativo.'
        }
    )

c_nutra/templates/profile/profile.html
{% extends "base.html" %}
{% load staticfiles %}
{% load widget_tweaks %}
<!DOCTYPE html>

{% block head %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/profile.css'%}">
  <link rel="stylesheet" href="//code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css">
{% endblock %}
{% block body %}
	<div class="wrapper" style="padding: 50px 5%;">
		<div class="page-header">
		  <h1>Mi Perfil <small>{{ user.username }}</small></h1>
		</div>

		<div class="row" style="margin: 0">
			<form action="." method="POST" class="list-group col-md-5">
				{% csrf_token %}
				<div class="list-group-item active">
					<h4 class="list-group-item-heading">Usuario</h4>
				</div>
				<div class="list-group-item">
					<h4 class="list-group-item-heading">Username
						<a id="edit_username" style="float:right">
							<i class="fa fa-fw fa-15 fa-pencil-square-o"></i>
						</a>
					</h4>
					<p id="username" class="list-group-item-text">{{ user.username }}</p>
					{{ form_user.username|attr:"class:form-control new_field" }}
				</div>
				<div class="list-group-item">
					<h4 class="list-group-item-heading">Email
						<a id="edit_email" style="float:right">
							<i class="fa fa-fw fa-15 fa-pencil-square-o"></i>
						</a>
					</h4>
					<p id="email" class="list-group-item-text">{{ user.email }}</p>
					{{ form_user.email|attr:"class:form-control new_field" }}
				</div>
				<div class="list-group-item">
					<h4 class="list-group-item-heading">Nombre
						<a id="edit_first_name" style="float:right">
							<i class="fa fa-fw fa-15 fa-pencil-square-o"></i>
						</a>
					</h4>
					<p id="first_name" class="list-group-item-text">{{ user.first_name }}</p>
					{{ form_user.first_name|attr:"class:form-control new_field" }}
				</div>
				<div class="list-group-item">
					<h4 class="list-group-item-heading">Apellido
						<a id="edit_last_name" style="float:right">
							<i class="fa fa-fw fa-15 fa-pencil-square-o"></i>
						</a>
					</h4>
					<p id="last_name" class="list-group-item-text">{{ user.last_name }}</p>
					{{ form_user.last_name|attr:"class:form-control new_field" }}
				</div>
				{% if messages and not profile_messages %}
				<div class="messages list-group-item">
				    {% for message in messages %}
						{% if message.level == 40 %}
				    		<p><i class="fa fa-exclamation" style="color: red"></i>  {{ message }}</p>
			    		{% else %}
			    			<p><i class="fa fa-check" style="color: green"></i>  {{ message }}</p>
			    		{% endif %}
				    {% endfor %}
				</div>
				{% endif %}
				<div id="submit_user" class="list-group-item text-center">
					<input type="hidden" name="user-form"/>
					<button class="btn btn-danger" onclick="window.location.reload();">Cancelar</button>
					<button type="submit" class="btn btn-primary">Aceptar</button>
				</div>
			</form>

			<form action="." method="POST" class="list-group col-md-5 col-md-offset-1">
				{% csrf_token %}
				<div class="list-group-item active">
					<h4 class="list-group-item-heading">Perfil
					</h4>
				</div>
				<div class="list-group-item">
					<h4 class="list-group-item-heading">Edad
						<a id="edit_date" style="float:right">
							<i class="fa fa-fw fa-15 fa-pencil-square-o"></i>
						</a>
					</h4>
					<p id="date" class="list-group-item-text">{{ profile.calculate_age }}</p>
					{{ form_profile.birthday|attr:"class:form-control new_field" }}
				</div>
				<div class="list-group-item">
					<h4 class="list-group-item-heading">Genero
					<a id="edit_gender" style="float:right">
							<i class="fa fa-fw fa-15 fa-pencil-square-o"></i>
						</a>
					</h4>
					<p id="gender" class="list-group-item-text">
						{% if profile.gender == 'M' %}
							Masculino
						{% elif profile.gender == 'F' %}
							Femenino
						{% endif %}
					</p>
					{{ form_profile.gender|attr:"class:form-control new_field" }}
				</div>
				<div class="list-group-item">
					<h4 class="list-group-item-heading">Altura
						<a id="edit_height" style="float:right">
							<i class="fa fa-fw fa-15 fa-pencil-square-o"></i>
						</a>
					</h4>
					<p id="height" class="list-group-item-text">
						{{ profile.height }}
					</p>
					{{ form_profile.height|attr:"class:form-control new_field" }}
				</div>
				<div class="list-group-item">
					<h4 class="list-group-item-heading">Peso
						<a id="edit_weight" style="float:right">
							<i class="fa fa-fw fa-15 fa-pencil-square-o"></i>
						</a>
					</h4>
					<p id="weight" class="list-group-item-text">
						{{ profile.weight }}
					</p>
					{{ form_profile.weight|attr:"class:form-control new_field" }}
				</div>
				<div class="list-group-item">
					<h4 class="list-group-item-heading">Diametro del Codo
						<a id="edit_elbow" style="float:right">
							<i class="fa fa-fw fa-15 fa-pencil-square-o"></i>
						</a>
					</h4>
					<p id="elbow" class="list-group-item-text">
						{{ profile.elbow_diameter }}
					</p>
					{{ form_profile.elbow_diameter|attr:"class:form-control new_field" }}
				</div>
				{% if messages and profile_messages %}
				<div class="messages list-group-item">
				    {% for message in messages %}
						{% if message.level == 40 %}
				    		<p><i class="fa fa-exclamation" style="color: red"></i>  {{ message }}</p>
			    		{% else %}
			    			<p><i class="fa fa-check" style="color: green"></i>  {{ message }}</p>
			    		{% endif %}
				    {% endfor %}
				</div>
				{% endif %}
				<div id="submit_profile" class="list-group-item text-center">
					<input type="hidden" name="profile-form"/>
					<button class="btn btn-danger" onclick="window.location.reload();">Cancelar</button>
					<button type="submit" class="btn btn-primary">Aceptar</button>
				</div>
		</form>
	</div>
	

{% endblock %}

{% block scripts %}
	<script>
		$("#edit_username").on('click', function() {
			$('#username').hide();
	   		$("#id_username").show();
	   		$('#submit_user').show();
		});
		$("#edit_email").on('click', function() {
			$('#gender').hide();
	   		$("#id_email").show();
	   		$('#submit_user').show();
		});
		$("#edit_first_name").on('click', function() {
			$('#height').hide();
	   		$("#id_first_name").show();
	   		$('#submit_user').show();
		});
		$("#edit_last_name").on('click', function() {
			$('#weight').hide();
	   		$("#id_last_name").show();
	   		$('#submit_user').show();
		});
	</script>
	<script>
		$("#edit_date").on('click', function() {
			$('#date').hide();
	   		$("#id_birthday").show();
	   		$('#submit_profile').show();
		});
		$("#edit_gender").on('click', function() {
			$('#gender').hide();
	   		$("#id_gender").show();
	   		$('#submit_profile').show();
		});
		$("#edit_height").on('click', function() {
			$('#height').hide();
	   		$("#id_height").show();
	   		$('#submit_profile').show();
		});
		$("#edit_weight").on('click', function() {
			$('#weight').hide();
	   		$("#id_weight").show();
	   		$('#submit_profile').show();
		});
		$("#edit_elbow").on('click', function() {
			$('#elbow').hide();
	   		$("#id_elbow_diameter").show();
	   		$('#submit_profile').show();
		});
	</script>
	<script src="//code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
	<script>
	  $(function() {
	    $( "#id_birthday" ).datepicker({
				dateFormat: "dd-mm-yy"});
	  });

  </script>
{% endblock %}

c_nutra/templates/profile/stats.html
{% extends "base.html" %}
{% load staticfiles %}
{% load widget_tweaks %}
<!DOCTYPE html>

{% block head %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/profile.css'%}">
{% endblock %}
{% block body %}
<div class="wrapper" style="padding: 50px 5%;">
	<div class="page-header">
		<h1>Mis Valores <small>{{ user.username }}</small></h1>
	</div>

<div class="row" style="margin: 0">
	<div class="col-md-6">
		<h2>Su indice de masa corporal es {{ bmi }}</h2> 
		{% if bmi < 18.5 %}
			<p>Usted esta por debajo del peso esperado en una persona de sus proporciones.</p>
		{% elif 18.5 <= bmi < 25 %}
			<p>Usted esta en rango del peso esperado en una persona de sus proporciones.</p>
		{% elif 25 <= bmi < 30 %}
			<p>Usted esta por encima del peso esperado en una persona de sus proporciones.</p>
		{% elif 30 <= bmi %}
			<p>Usted esta por muy por encima del peso esperado en una persona de sus proporciones.</p>
		{% endif %}
	</div>
	<div class="col-md-6">
		<h2>Nota</h2>
		<p>El IMC es un índice o valor que permite establecer si se está en un peso saludable, con bajo peso, sobrepeso o se sufre de obesidad en funcion de su peso y altura.</p>
		<p>Esta medida no es perfecta ya que sólo depende de la altura y el peso, no teniendo en cuenta los niveles de adiposidad diferentes según la edad, la actividad física y el sexo.</p>
	</div>
</div>
<hr style="padding: 0 5%;">
<div class="row" style="margin: 0">
	<div class="col-md-6">
		<h2>Su requerimiento calorico diario es {{ dem }}</h2>
	</div>
	<div class="col-md-6">
		<h2>Nota</h2>
		<p>Para una determinacion mas acertada es necesario llevar a cabo examenes fisiologicos individuales.</p>
		<p>Un nutricionista podra ayudarlo para estos examenes.</p>
	</div>
	</div>
	</div>
{% endblock %}

{% block scripts %}
{% endblock %}