c_nutra/apps/surveys/urls.py
from django.conf.urls import patterns, include, url
#from apps.surveys import views

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
#import settings

admin.autodiscover()
#media_url = settings.MEDIA_URL.lstrip('/').rstrip('/')

urlpatterns = patterns('',
	# Examples:
	url(r'^$', 'apps.surveys.views.Index', name='survey_index'),
	url(r'^survey/(?P<id>\d+)/$', 'apps.surveys.views.SurveyDetail', name='survey_detail'),
	url(r'^confirm/(?P<uuid>\w+)/$', 'apps.surveys.views.Confirm', name='confirmation'),


	# Uncomment the admin/doc line below to enable admin documentation:
	url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

	# Uncomment the next line to enable the admin:
	url(r'^admin/', include(admin.site.urls)),
)

# media url hackery. le sigh. 
#urlpatterns += patterns('',
#    (r'^%s/(?P<path>.*)$' % media_url, 'django.views.static.serve',
#     { 'document_root': settings.MEDIA_ROOT, 'show_indexes':True }),
#)

c_nutra/config/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^$', TemplateView.as_view(
                           template_name='home.html'), name='home'),
                       url(r'^grappelli/', include('grappelli.urls')), # grappelli URLS                       
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^password-reset/', include(
                           'password_reset.urls')),

                       # Accounts urls
                       url(r'accounts/login/$',
                           'django.contrib.auth.views.login', name='login'),
                       url(r'accounts/logout/$', 'django.contrib.auth.views.logout',
                           {'next_page': 'home'}, name='logout'),
                       url(r'accounts/register/$',
                           'apps.users.views.user_register', name='register'),
                       url(r'accounts/profile/$',
                           'apps.users.views.user_profile', name='profile'),
                       url(r'accounts/stats/$',
                           'apps.users.views.user_stats', name='stats'),

                       # Surveys urls
                       url(r'^surveys/', include(
                           'apps.surveys.urls', namespace="surveys")),
                       )

# Uncomment the next line to serve media files in dev.
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns += patterns('',
#                             url(r'^__debug__/', include(debug_toolbar.urls)),
#                             )

c_nutra/apps/surveys/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.core.exceptions import ValidationError

class Survey(models.Model):
	name = models.CharField('Nombre', max_length=400)
	description = models.TextField('Descripción')

	class Meta:
		verbose_name = ('Encuesta')
		verbose_name_plural = ('Encuestas')	

	def __unicode__(self):
		return (self.name)

	def questions(self):
		if self.pk:
			return Question.objects.filter(survey=self.pk)
		else:
			return None

class Category(models.Model):
	name = models.CharField('Nombre', max_length=400)
	survey = models.ForeignKey(Survey)

	class Meta:
		verbose_name = ('Categoria')
		verbose_name_plural = ('Categorias')	

	def __unicode__(self):
		return (self.name)

def validate_list(value):
	'''takes a text value and verifies that there is at least one comma '''
	values = value.split(',')
	if len(values) < 2:
		raise ValidationError("EL campo seleccionado requiere una lista asociada de opciones, las opciones deben contener mas de un elemento.")

class Question(models.Model):

	class Meta:
		verbose_name = ('Pregunta')
		verbose_name_plural = ('Preguntas')

	TEXT = 'Texto'
	RADIO = 'radio'
	SELECT = 'select'
	SELECT_MULTIPLE = 'select-multiple'
	INTEGER = 'integer'

	QUESTION_TYPES = (
		(TEXT, 'Texto'),
		(RADIO, 'Radio'),
		(SELECT, 'Selección'),
		(SELECT_MULTIPLE, 'Selección múltiple'),
		(INTEGER, 'Numérica'),
	)

	text = models.TextField('Texto')
	required = models.BooleanField('Requerido')
	category = models.ForeignKey(Category, blank=True, null=True) 
	survey = models.ForeignKey(Survey)
	question_type = models.CharField(max_length=200, choices=QUESTION_TYPES, default=TEXT)
	# the choices field is only used if the question type 
	choices = models.TextField(blank=True, null=True,
		help_text='Si el tipo de pregunta es "radio", "selección" o "selección múltiple" provea un lista separada por comas de las opciones para esta pregunta.')

	def save(self, *args, **kwargs):
		if (self.question_type == Question.RADIO or self.question_type == Question.SELECT 
			or self.question_type == Question.SELECT_MULTIPLE):
			validate_list(self.choices)
		super(Question, self).save(*args, **kwargs)

	def get_choices(self):
		''' parse the choices field and return a tuple formatted appropriately
		for the 'choices' argument of a form widget.'''
		choices = self.choices.split(',')
		choices_list = []
		for c in choices:
			c = c.strip()
			choices_list.append((c,c))
		choices_tuple = tuple(choices_list)
		return choices_tuple

	def __unicode__(self):
		return (self.text)

class Response(models.Model):
	# a response object is just a collection of questions and answers with a
	# unique interview uuid
	created = models.DateTimeField('Creada', auto_now_add=True)
	updated = models.DateTimeField('Actualizada', auto_now=True)
	survey = models.ForeignKey(Survey)
	interviewer = models.CharField('Nombre del entrevistador', max_length=400)
	interviewee = models.CharField('Nombre del entrevistado', max_length=400)
	conditions = models.TextField('Condiciones durante la entrevista', blank=True, null=True)
	comments = models.TextField('Comentarios adicionales', blank=True, null=True)
	interview_uuid = models.CharField("Identificador único de la entrevista", max_length=36)

	class Meta:
		verbose_name = ('Respuesta')
    	verbose_name_plural = ('Respuestas')

	def __unicode__(self):
		return ("response %s" % self.interview_uuid)

class AnswerBase(models.Model):
	question = models.ForeignKey(Question)
	response = models.ForeignKey(Response)
	created = models.DateTimeField('Creada', auto_now_add=True)
	updated = models.DateTimeField('Actualizada', auto_now=True)

	class Meta:
		verbose_name = ('Respuesta')
    	verbose_name_plural = ('Respuestas')	

# these type-specific answer models use a text field to allow for flexible
# field sizes depending on the actual question this answer corresponds to. any
# "required" attribute will be enforced by the form.
class AnswerText(AnswerBase):
	body = models.TextField(blank=True, null=True)

class AnswerRadio(AnswerBase):
	body = models.TextField(blank=True, null=True)

class AnswerSelect(AnswerBase):
	body = models.TextField(blank=True, null=True)

class AnswerSelectMultiple(AnswerBase):
	body = models.TextField(blank=True, null=True)

class AnswerInteger(AnswerBase):
	body = models.IntegerField(blank=True, null=True)

c_nutra/apps/surveys/forms.py
from django import forms
from django.forms import models
from apps.surveys.models import Question, Category, Survey, Response, AnswerText, AnswerRadio, AnswerSelect, AnswerInteger, AnswerSelectMultiple
from django.utils.safestring import mark_safe
import uuid

# blatantly stolen from 
# http://stackoverflow.com/questions/5935546/align-radio-buttons-horizontally-in-django-forms?rq=1
class HorizontalRadioRenderer(forms.RadioSelect.renderer):
  def render(self):
    return mark_safe(u'\n'.join([u'%s\n' % w for w in self]))


class ResponseForm(models.ModelForm):
	class Meta:
		model = Response	
		fields = ('interviewer', 'interviewee', 'conditions', 'comments')

	def __init__(self, *args, **kwargs):
		# expects a survey object to be passed in initially
		survey = kwargs.pop('survey')
		self.survey = survey
		super(ResponseForm, self).__init__(*args, **kwargs)
		self.uuid = random_uuid = uuid.uuid4().hex	

		# add a field for each survey question, corresponding to the question
		# type as appropriate.
		data = kwargs.get('data')
		for q in survey.questions():
			if q.question_type == Question.TEXT:
				self.fields["question_%d" % q.pk] = forms.CharField(label=q.text, 
					widget=forms.Textarea)
			elif q.question_type == Question.RADIO:
				question_choices = q.get_choices()
				self.fields["question_%d" % q.pk] = forms.ChoiceField(label=q.text, 
					widget=forms.RadioSelect(renderer=HorizontalRadioRenderer), 
					choices = question_choices)
			elif q.question_type == Question.SELECT:
				question_choices = q.get_choices()
				# add an empty option at the top so that the user has to
				# explicitly select one of the options
				question_choices = tuple([('', '-------------')]) + question_choices
				self.fields["question_%d" % q.pk] = forms.ChoiceField(label=q.text, 
					widget=forms.Select, choices = question_choices)
			elif q.question_type == Question.SELECT_MULTIPLE:
				question_choices = q.get_choices()
				self.fields["question_%d" % q.pk] = forms.MultipleChoiceField(label=q.text, 
					widget=forms.CheckboxSelectMultiple, choices = question_choices)
			elif q.question_type == Question.INTEGER:
				self.fields["question_%d" % q.pk] = forms.IntegerField(label=q.text)				
			
			# if the field is required, give it a corresponding css class.
			if q.required:
				self.fields["question_%d" % q.pk].required = True
				self.fields["question_%d" % q.pk].widget.attrs["class"] = "required"
			else:
				self.fields["question_%d" % q.pk].required = False
				
			# add the category as a css class, and add it as a data attribute
			# as well (this is used in the template to allow sorting the
			# questions by category)
			if q.category:
				classes = self.fields["question_%d" % q.pk].widget.attrs.get("class")
				if classes:
					self.fields["question_%d" % q.pk].widget.attrs["class"] = classes + (" cat_%s" % q.category.name)
				else:
					self.fields["question_%d" % q.pk].widget.attrs["class"] = (" cat_%s" % q.category.name)
				self.fields["question_%d" % q.pk].widget.attrs["category"] = q.category.name


			# initialize the form field with values from a POST request, if any.
			if data:
				self.fields["question_%d" % q.pk].initial = data.get('question_%d' % q.pk)

	def save(self, commit=True):
		# save the response object
		response = super(ResponseForm, self).save(commit=False)
		response.survey = self.survey
		response.interview_uuid = self.uuid
		response.save()

		# create an answer object for each question and associate it with this
		# response.
		for field_name, field_value in self.cleaned_data.iteritems():
			if field_name.startswith("question_"):
				# warning: this way of extracting the id is very fragile and
				# entirely dependent on the way the question_id is encoded in the
				# field name in the __init__ method of this form class.
				q_id = int(field_name.split("_")[1])
				q = Question.objects.get(pk=q_id)
				
				if q.question_type == Question.TEXT:
					a = AnswerText(question = q)
					a.body = field_value
				elif q.question_type == Question.RADIO:
					a = AnswerRadio(question = q)	
					a.body = field_value
				elif q.question_type == Question.SELECT:
					a = AnswerSelect(question = q)	
					a.body = field_value
				elif q.question_type == Question.SELECT_MULTIPLE:
					a = AnswerSelectMultiple(question = q)	
					a.body = field_value
				elif q.question_type == Question.INTEGER:	
					a = AnswerInteger(question = q)	
					a.body = field_value
				print "creating answer to question %d of type %s" % (q_id, a.question.question_type) 
				print a.question.text
				print 'answer value:'
				print field_value
				a.response = response
				a.save()
		return response

c_nutra/apps/surveys/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.core import urlresolvers
from django.contrib import messages
import datetime
import settings

from models import Question, Survey, Category
from forms import ResponseForm


def Index(request): 
        survey_list = Survey.objects.all()
        context = {'survey_list': survey_list}
        return render(request, 'surveys/index.html', context)


def SurveyDetail(request, id):
	survey = Survey.objects.get(id=id)
	category_items = Category.objects.filter(survey=survey)
	categories = [c.name for c in category_items]
	print 'categories for this survey:'
	print categories
	if request.method == 'POST':
		form = ResponseForm(request.POST, survey=survey)
		if form.is_valid():
			response = form.save()
                        return HttpResponseRedirect("/surveys/")
			#return HttpResponseRedirect("/surveys/confirm/%s" % response.interview_uuid)
	else:
		form = ResponseForm(survey=survey)
		print form
		# TODO sort by category
	return render(request, 'surveys/survey.html', {'response_form': form, 'survey': survey, 'categories': categories})

def Confirm(request, uuid):
        email = "micafe.go@gmail.com"
	#email = settings.support_email
	return render(request, 'surveys/confirm.html', {'uuid':uuid, "email": email})

c_nutra/templates/surveys/confirm.html
{% extends 'base.html' %}

{% block body %}

Thanks! Your confirmation code is {{uuid}}. Use this to refer to your response. 
<!--In case you have any questions, contact {{ email }}-->
{% endblock %}

c_nutra/templates/surveys/index.html
{% extends "base.html" %}
{% load staticfiles %}

<!DOCTYPE html>

{% block body %}
<div class="sub-container">
	<div id="survey_list-wrapper" style="margin-top: 100px;">
		<h1>Encuestas disponibles</h1>

		{% if survey_list %}

	    <ul class="list-unstyled">
	      {% for survey in survey_list %}
	        <li ><a href="{% url 'surveys:survey_detail' survey.id %}" class="survey-name">
	        {{ survey.name }}</a></li>
	      {% endfor %}
	    </ul>

	  {% else %}

	    <p> No hay encuestas disponibles. </p>

	  {% endif %}

	</div>
</div>	

{% endblock %}

c_nutra/templates/surveys/survey.html
{% extends 'base.html' %}
{% load survey_extras %}

{% block body %}
<div class="sub-container">
	<div id="survey-wrapper" style="margin-top: 100px; margin-left: 30px;">
		<h1>{{survey.name|title}}</h1>
		<div class="survey-description">
			{{survey.description|safe}}
		</div>

		<div>
			<form action="{% url 'surveys:survey_detail' survey.id %}" method="post">{% csrf_token %}

				<div class="category-container">

				<div class="field-wrapper question-required">
					{{ response_form.interviewer.errors }}
					<span class="asterix"> * </span>{{ response_form.interviewer.label_tag }}
					<span class="form-help-text">{{ response_form.interviewer.help_text}}</span>
					<div class="form-field-body">
						{{ response_form.interviewer }}
					</div>
				</div>

				<div class="field-wrapper question-required">
					{{ response_form.interviewee.errors }}
					<span class="asterix"> * </span>{{ response_form.interviewee.label_tag }}
					<span class="form-help-text">{{ response_form.interviewee.help_text}}</span>
					<div class="form-field-body">
						{{ response_form.interviewee }}
					</div>
				</div>

<!-- 				<div class="field-wrapper">
					{{ response_form.conditions.errors }}
					{{ response_form.conditions.label_tag }}
					<span class="form-help-text">{{ response_form.conditions.help_text}}</span>
					<div class="form-field-body">
						{{ response_form.conditions }}
					</div>
				</div> -->

				<div class="field-wrapper">
					{{ response_form.comments.errors }}
					{{ response_form.comments.label_tag }}
					<span class="form-help-text">{{ response_form.comments.help_text}}</span>
					<div class="form-field-body">
						{{ response_form.comments }}
					</div>
				</div>
			</div>

				<ol class="survey-questions">
				{% for category in categories %}
					<h3 class="collapsible">{{category|title}} Questions<span></span></h3>
					<div class="category-container">
					{% for field in response_form %}
						{% if field.field.widget.attrs.category == category %}
							<li class="q-item" value="{% counter %}">
							{% if field.field.required %} 
							<div class="field-wrapper question-required"> 
								{{ field.errors }}
								<span class="asterix"> * </span><label class="label-inline">{{ field.label }}</label>
							{% else %} 
							<div class="field-wrapper"> 
								{{ field.errors }}
								<label class="label-inline">{{ field.label }}</label>
							{% endif %}
								<span class="form-help-text">{{ field.help_text}}</span>
								<div class="form-field-body">
									{{ field }}
								</div>
							</div>
							</li>
						{% endif %}
					{% endfor %}
					</div>
				{% endfor %}
				</ol>

				<button class="btn btn-default" type="submit">Guardar entrevista</button>
			</form>
		</div>
	</div>
</div>

{% endblock %}

{% block extrajs %}
	<script src="/media/js/jquery.collapsible.js"></script>	
	<script type="text/javascript">
		$(document).ready(function() {
			//collapsible management
			$('.collapsible').collapsible({defaultOpen: 'response_metadata'});
		});
	</script>
{% endblock %}

c_nutra/templates/surveys/survey_base.html
{% extends "base.html" %}
<!DOCTYPE html>
<html lang="en">
  <head>
	<meta charset="utf-8">
	<title>Embassy Network</title>
	<!-- responsive support -->
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="The Embassy Network is a housing network reinventing home for the creative age.">
	<meta name="author" content="Jessy Kate Schingler">

	<!-- Le styles -->
	<link href="/media/css/bootstrap.css" rel="stylesheet">
	<link href="/media/css/custom.css" rel="stylesheet">
	<link href="/media/css/bootstrap-responsive.css" rel="stylesheet">

	<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
	<!--[if lt IE 9]>
	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->

	<!-- Le fav and touch icons -->
	<link rel="shortcut icon" href="/ico/favicon.ico">
	<link rel="apple-touch-icon-precomposed" sizes="114x114" href="/ico/apple-touch-icon-114-precomposed.png">
	<link rel="apple-touch-icon-precomposed" sizes="72x72" href="/ico/apple-touch-icon-72-precomposed.png">
	<link rel="apple-touch-icon-precomposed" href="/ico/apple-touch-icon-57-precomposed.png">

  </head>

  <body>

	<!-- Part 1: Wrap all page content here -->
	{% block wrapper %}
	<div id="wrap">
	{% endblock %}

	<div class="container" id="container-main">
	{% block body %}
	{% endblock %}

	<div id="push"></div> <!-- #push goes inside container -->
	</div> <!-- /container -->
	</div> <!-- end #wrap -->
	
	<footer class="footer">
		<div class="container">
	{% block footer %}
	{% endblock %}
	</container>
	</footer>
	<!-- Le javascript -->
	<link rel="stylesheet" href="/media/css/flick/jquery-ui-1.9.1.custom.css" />    
	<script src="/media/js/jquery-1.8.2.js"></script>
	<script src="/media/js/jquery-ui-1.9.1.custom.js"></script>	
	<script src="/media/js/bootstrap.js"></script>
	<script>
		// use the jquery UI datepicker on all pages with the datepicker class:
		$(".datepicker").datepicker({ minDate: 0});
	</script>
	{% block extrajs %}
	{% endblock %}
  </body>
</html>

c_nutra/templates/surveys/surveys.html
{% extends "base.html" %}
{% load staticfiles %}

{% block head %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/polls.css'%}">
{% endblock %}

{% block body%}

<div class="polls">

    <!-- Default panel contents -->
  <div class="page-header">
    <h1>Encuestas </h1>
  </div>

  <!-- List group -->
  <div class="panel-group" id="accordion">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
            Encuesta1
          </a>
        </h4>
      </div>
      <div id="collapseOne" class="panel-collapse collapse">
        <div class="panel-body">
          Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
          <button class="btn">Tomar</button>
        </div>
      </div>
    </div>
    <div class="panel panel-info">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
            Encuesta2
          </a>
        </h4>
      </div>
      <div id="collapseTwo" class="panel-collapse collapse">
        <div class="panel-info">
          Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
          <button class="btn">Tomar</button>
        </div>
      </div>
    </div>
    <div class="panel panel-info">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
            Encuesta3
          </a>
        </h4>
      </div>
      <div id="collapseThree" class="panel-collapse collapse">
        <div class="panel-body">
          Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
          <button class="btn">Tomar</button>
        </div>
      </div>
    </div>
  </div>

</div>

{% endblock %}