c_nutra/apps/surveys/urls.py
from django.conf.urls import patterns, include, url
#from apps.surveys import views

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
#import settings

admin.autodiscover()
#media_url = settings.MEDIA_URL.lstrip('/').rstrip('/')

urlpatterns = patterns('',
	# Examples:
	url(r'^$', 'apps.surveys.views.Index', name='survey_index'),
	url(r'^survey/(?P<id>\d+)/$', 'apps.surveys.views.SurveyDetail', name='survey_detail'),
	url(r'^confirm/(?P<uuid>\w+)/$', 'apps.surveys.views.Confirm', name='confirmation'),


	# Uncomment the admin/doc line below to enable admin documentation:
	url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

	# Uncomment the next line to enable the admin:
	url(r'^admin/', include(admin.site.urls)),
)

# media url hackery. le sigh. 
#urlpatterns += patterns('',
#    (r'^%s/(?P<path>.*)$' % media_url, 'django.views.static.serve',
#     { 'document_root': settings.MEDIA_ROOT, 'show_indexes':True }),
#)

c_nutra/config/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^$', TemplateView.as_view(
                           template_name='home.html'), name='home'),
                       url(r'^grappelli/', include('grappelli.urls')), # grappelli URLS                       
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^password-reset/', include(
                           'password_reset.urls')),

                       # Accounts urls
                       url(r'accounts/login/$',
                           'django.contrib.auth.views.login', name='login'),
                       url(r'accounts/logout/$', 'django.contrib.auth.views.logout',
                           {'next_page': 'home'}, name='logout'),
                       url(r'accounts/register/$',
                           'apps.users.views.user_register', name='register'),
                       url(r'accounts/profile/$',
                           'apps.users.views.user_profile', name='profile'),
                       url(r'accounts/stats/$',
                           'apps.users.views.user_stats', name='stats'),

                       # Surveys urls
                       url(r'^surveys/', include(
                           'apps.surveys.urls', namespace="surveys")),
                       )

# Uncomment the next line to serve media files in dev.
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns += patterns('',
#                             url(r'^__debug__/', include(debug_toolbar.urls)),
#                             )

c_nutra/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8"> 
        <title>C-Nutra {% block title %}{% endblock%}</title>
        <meta name="generator" content="C-Nutra" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet">
        
        <!--[if lt IE 9]>
          <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->

        <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'css/base.css'%}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/navbar.css'%}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/survey.css'%}">
        {% block head %}{% endblock %}
    </head>
    <body>
      <div class="container">
        <div class="navbar-wrapper">
          <div class="navbar navbar-inverse navbar-static-top">

            <div class="navbar-header">
              <a class="navbar-toggle" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </a>
              <a class="navbar-brand" href="/">C-Nutra</a>
            </div>
            <div class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li class="active"><a href="#">Inicio</a></li>
                <li><a href="#">Alimentos</a></li>
                <li><a href="{% url 'surveys:survey_index' %}">Encuestas</a></li>
                <li><a href="#">Recetas</a></li>
                <li><a href="#contact">Contacto</a></li>
              </ul>
              {% if user.is_authenticated %}

                <ul class="nav navbar-nav navbar-right " style="margin-right:0;">
                    <li class="user_bar"> Bienvenido, {{ user.username }} </li>
                  <li class="user_bar">
                      <div class="btn-group">
                        <a class="btn dropdown-toggle" data-toggle="dropdown" href="#" style="color: white;">

                          <span class="caret"></span>
                        </a>
            
                        <ul class="dropdown-menu" style="top: 127%">
                          <!-- dropdown menu links -->
                          <li role="presentation"><a role="menuitem" tabindex="-1" href="{% url 'profile' %}">Mi Perfil</a></li>
                          <li class="divider"></li>
                          <li role="presentation"><a role="menuitem" tabindex="-1" href="{% url 'stats' %}">Mis valores</a></li>
                          <li class="divider"></li>
                          <li role="presentation"><a role="menuitem" tabindex="-1" href="{% url 'logout' %}">Salir</a></li>
                        </ul>
                      </div>
                    </li>

                    </ul>
                  {% else %}
                    <ul class="nav navbar-nav navbar-right " style="margin-right:0;">

                      <li class="user_bar"> Ingresar </li>

                      <li class="user_bar">
                        <div class="btn-group">
                          <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
                            <!--Ingresa-->
                            <i class="fa fa-caret-down" style="color: white;"></i>
                          </a>
            
                          <ul class="dropdown-menu" style="top: 127%">
                            <!-- dropdown menu links -->
                            <li role="presentation"><a role="menuitem" tabindex="-1" href="{% url 'register' %}">Registrarse</a></li>
                            <li role="presentation"><a role="menuitem" tabindex="-1" href="{% url 'login' %}">Login</a></li>
                          </ul>
                        </div>
                      </li>

                    </ul>
              {% endif %}

            </div>

          </div>
        </div><!-- /container -->
      </div><!-- /navbar wrapper -->

      {% block body %}

        {% block content %}

        {% endblock %}

      {% endblock %}

    <!-- FOOTER -->
    <footer>
      <!-- <p>Informacion importante de la USB.</p> -->
    </footer>

  </div><!-- /.container -->

  <script type='text/javascript' src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>


  <script type='text/javascript' src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>


  <script type='text/javascript'>
      $(document).ready(function() {
           $('.carousel').carousel({
               interval: 5000
           })
      });    
      </script>
  {% block scripts %}{% endblock %}
  
</body>
</html>

c_nutra/templates/home.html
{% extends "base.html" %}
{% load staticfiles %}

{% block head %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/home.css'%}">
{% endblock %}


{% block body %}
<center>
  <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
      <li data-target="#carousel-example-generic" data-slide-to="1"></li>
      <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <div class="item active">
        <img src="{% static '/assets/img/home/ca1.png' %}" alt="...">
        <div class="carousel-caption">
          ...
        </div>
      </div>
      <div class="item">
        <img src="{% static '/assets/img/home/ca2.png' %}" alt="...">
        <div class="carousel-caption">
          ...
        </div>
      </div>
      ...
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
    </a>
    <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
    </a>
  </div>
</center>


<!-- Marketing messaging and featurettes
  ================================================== -->
  <!-- Wrap the rest of the page in another container to center all the content. -->

  <div class="container marketing">

    <!-- Three columns of text below the carousel -->
    <div class="row">
      <div class="col-md-3 text-center">
        <img class="img-circle" src="/assets/img/home/f1.png">
        <h2>Alimentos</h2>
        <p>Aquí encontraraś informacion sobre los valores nutricionales 
        de diversos alimentos de consumo común.</p>
      </div>
      <div class="col-md-3 text-center">
        <a href="{% url 'surveys:survey_index' %}"><img  class="img-circle" src="/assets/img/home/p.png"></a>
        <h2>Encuestas</h2>
        <p>Completa estas encuestas para saber mas sobre como comer mejor y llevar
        una vida maś saludable.</p>
      </div>
      <div  class="col-md-3 text-center">
        <img href="/" class="img-circle" src="/assets/img/home/c.png">
        <h2>Recetas</h2>
        <p>Descubre nuevos platos de sencilla preparación para variar tu menú.</p>
      </div>
      <div  class="col-md-3 text-center">
        <img href="/" class="img-circle" src="/assets/img/home/c2.png">
        <h2>Herramientas</h2>
        <p>Calcula tu índice de masa corporal, estima tu requerimiento nutricional y más.</p>
      </div>      
    </div><!-- /.row -->

{% endblock %}